<?php

/**
 * Copyright [2014] [Dexxtz]
 *
 * @package   Dexxtz_StoreMaintenance
 * @author    Dexxtz
 * @license   http://www.apache.org/licenses/LICENSE-2.0
 */
?>
<?php
$page = Mage::getSingleton('Mage_Page_Block_Html');
$head = Mage::getSingleton('Mage_Page_Block_Html_Head');
$title = (Mage::getStoreConfig('storemaintenance/dexxtz/title')) ? Mage::getStoreConfig('storemaintenance/dexxtz/title') : 'Store Maintenance';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $page->getLang();?>" lang="<?php echo $page->getLang();?>">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->__($title);?></title>
<meta name="description" content="<?php echo htmlspecialchars($head->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($head->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($head->getRobots()) ?>" />
<link rel="icon" href="<?php echo $head->getFaviconFile();?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $head->getFaviconFile();?>" type="image/x-icon" />
<head>
<body>
<?php
	// capturing the identification of the selected static block
	$blockStatic = Mage::getStoreConfig('storemaintenance/dexxtz/block_static'); 
	
	//displays the contents of the static block
	echo Mage::getSingleton('core/layout')->createBlock('cms/block')->setBlockId($blockStatic)->toHtml() . "\n";
?>
</body>
</html>